name: Workflow Sync

on:
  push:
    branches:
      - main
env:
  DRY_RUN: false
  REPOSITORIES: |
    bd-R/bdutilities

  WORKFLOW_FILES: |
    ci/os/Ubu-Dev-Dec.yml=.github/workflows/Ubu-Dev-Dec.yml
    ci/os/Win-Dev-Dec.yml=.github/workflows/Win-Dev-Dec.yml
    ci/os/Mac-Dev-Dec.yml=.github/workflows/Mac-Dev-Dec.yml

jobs:
  Github_Workflow_Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.SYNCWORKFLOW }}
