name: Workflow Sync

on:
  push:
    branches:
      - main
env:
  DRY_RUN: false
  REPOSITORIES: |
    bd-R/bdutilities
    bd-R/bdutilities.app
    bd-R/bddwc
    bd-R/bddwc.app
    bd-R/bdchecks
    bd-R/bdchecks.app
    bd-R/bdclean
    bd-R/bddashboard

  WORKFLOW_FILES: |
    ci/os/Ubu-Mas-Mas.yml=.github/workflows/Ubu-Mas-Mas.yml
    ci/os/Win-Mas-Mas.yml=.github/workflows/Win-Mas-Mas.yml
    ci/os/Mac-Mas-Mas.yml=.github/workflows/Mac-Mas-Mas.yml
    ci/os/Ubu-Dev-Dev.yml=.github/workflows/Ubu-Dev-Dev.yml
    ci/os/Win-Dev-Dev.yml=.github/workflows/Win-Dev-Dev.yml
    ci/os/Mac-Dev-Dev.yml=.github/workflows/Mac-Dev-Dev.yml
    ci/os/Ubu-Dev-Mas.yml=.github/workflows/Ubu-Dev-Mas.yml
    ci/os/Win-Dev-Mas.yml=.github/workflows/Win-Dev-Mas.yml
    ci/os/Mac-Dev-Mas.yml=.github/workflows/Mac-Dev-Mas.yml
    github/.gitignore=.gitignore
    github/.Rbuildignore=.Rbuildignore

jobs:
  Github_Workflow_Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.SYNCWORKFLOW }}
